### PR TITLE
Update to new .Net core project files

### PR DESCRIPTION
**Pull request by chrismeller**
Gets rid of the old core-beta global.json and project.json files and switches to using the new .sln and .csproj versions.

Also gets rid of several things that were marked as internal that were causing builds to fail.

### CODE REVIEW

**Comment by rszemplinski** [comment]
How come you switched the access modifiers for the return object functions from internal to public?

**Comment by rszemplinski** [comment]
I know that it caused the builds to fail but I believe that's because you removed the assembly file that made those internals visible.

**Comment by chrismeller** [comment]
@rszemplinski Good catch. I accidentally wiped out InternalsVisibleTo when I got rid of all the other duplicate AssemblyInfo properties. I have restored that one and reverted the internal->public commit.

**Comment by ryandanthony** [comment]
Looks like https://github.com/EduSource/QuickBooks.Net/issues/1 should be resolved by this pull request. The nuget package will support netstandard1.6 AND net462...

**Comment by chrismeller** [comment]
Through some trial and error with appveyor, also cleaned up the build and package steps to get rid of the nuspec file and set both the assembly version and the package version to that of the appveyor build.

**Pull request merged**
